# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "syslog-health-monitor.fullname" . }}
  labels:
    {{- include "syslog-health-monitor.labels" . | nindent 4 }}
data:
  # This ConfigMap is currently minimal as primary configuration is passed
  # via command-line arguments in the DaemonSet, sourced from values.yaml.
  # It can be extended in the future if needed for more complex configurations
  # or scripts.
  #
  # Note: This ConfigMap is shared by both regular and kata DaemonSet variants.
  # Kata detection is handled by the labeler-module which sets the
  # "nvsentinel.dgxc.nvidia.com/kata.enabled" label on nodes. The DaemonSets
  # use nodeSelector to deploy the correct variant based on this label.
  # 
  # Previously, kata-specific journal tags (e.g., "-u containerd.service") were
  # conditionally added here, but these are no longer needed because:
  # 1. Kata detection happens at the deployment level via node labels
  # 2. Each DaemonSet variant (regular/kata) handles journal access differently:
  #    - Regular: mounts /var/log (file-based logs)
  #    - Kata: mounts /run/systemd/journal and /var/log/journal (systemd journal)
  # 3. The kata variant accesses the systemd journal directly, so it can read
  #    containerd logs without needing special tags or filters in the ConfigMap
  log_check_definitions.yaml: |
    checks:
      - name: "SysLogsXIDError"
        journalPath: "/nvsentinel/var/log/journal/"

      - name: "SysLogsSXIDError"
        journalPath: "/nvsentinel/var/log/journal/"

      - name: "SysLogsGPUFallenOff"
        journalPath: "/nvsentinel/var/log/journal/"
