# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "syslog-health-monitor.fullname" . }}-regular
  labels:
    {{- include "syslog-health-monitor.labels" . | nindent 4 }}
spec:
  updateStrategy:
    type: {{ .Values.updateStrategy }}
    {{- if eq .Values.updateStrategy "RollingUpdate"}}
    rollingUpdate:
      maxUnavailable: {{ .Values.maxUnavailable }}
    {{- end}}
  selector:
    matchLabels:
      {{- include "syslog-health-monitor.selectorLabels" . | nindent 6 }}
      nvsentinel.dgxc.nvidia.com/kata: "false"
  template:
    metadata:
      {{- with (.Values.global.podAnnotations | default .Values.podAnnotations) }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "syslog-health-monitor.selectorLabels" . | nindent 8 }}
        nvsentinel.dgxc.nvidia.com/kata: "false"
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: syslog-health-monitor
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.syslogHealthMonitor.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          args:
            - "--config-file"
            - "/etc/syslog-monitor/log_check_definitions.yaml"
            - "--polling-interval"
            - "{{ .Values.pollingInterval }}"
            - "--metrics-port"
            - "{{ .Values.global.metricsPort }}"
            {{- if .Values.global.syslogHealthMonitor.xidSideCar.enabled }}
            - "--xid-analyser-endpoint"
            - "http://localhost:8080"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: metrics
              containerPort: {{ .Values.global.metricsPort }}
          livenessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.global.metricsPort }}
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.global.metricsPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          env: 
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: config-volume
              mountPath: /etc/syslog-monitor
              readOnly: true
            - name: var-run-vol
              mountPath: /var/run/
            - name: syslog-state-vol
              mountPath: /var/run/syslog_health_monitor
            # Regular mode: Mount var/log directly
            - name: var-log-vol
              mountPath: /nvsentinel/var/log
              readOnly: true
            - name: proc-vol
              mountPath: /nvsentinel/proc
              readOnly: true
            - name: sys-vol
              mountPath: /nvsentinel/sys
              readOnly: true
        {{- if .Values.global.syslogHealthMonitor.xidSideCar.enabled }}
        - name: xid-analyzer-sidecar
          image: {{ .Values.global.syslogHealthMonitor.xidSideCar.image.repository }}:{{ .Values.global.syslogHealthMonitor.xidSideCar.image.tag }}
          imagePullPolicy: {{ .Values.global.syslogHealthMonitor.xidSideCar.image.pullPolicy }}
          ports:
            - name: http-api
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: PORT
              value: "8080"
        {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "syslog-health-monitor.fullname" . }}
        - name: var-run-vol
          hostPath:
            path: /var/run/nvsentinel
            type: DirectoryOrCreate
        - name: syslog-state-vol
          hostPath:
            path: /var/run/syslog_health_monitor
            type: DirectoryOrCreate
        # Regular mode: Direct var/log mount
        - name: var-log-vol
          hostPath:
            path: /var/log
            type: Directory
        - name: sys-vol
          hostPath:
            path: /sys
            type: Directory
        - name: proc-vol    
          hostPath:
            path: /proc
            type: Directory
      nodeSelector:
        nvsentinel.dgxc.nvidia.com/driver.installed: "true"
        nvsentinel.dgxc.nvidia.com/kata.enabled: "false"
        {{- with (.Values.global.nodeSelector | default .Values.nodeSelector) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with (.Values.global.affinity | default .Values.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (.Values.global.tolerations | default .Values.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
