
# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

replicaCount: 1

logLevel: info

image:
  repository: ghcr.io/nvidia/nvsentinel/fault-remediation
  pullPolicy: IfNotPresent
  tag: ""

resources: 
  limits:
    cpu: "200m"
    memory: "300Mi"
  requests:
    cpu: "200m"
    memory: "300Mi"

# Scheduling configuration
nodeSelector: {}
affinity: {}

podAnnotations: {}

# Special tolerations for fault remediation - allow running on nodes with any taints for log collection
tolerations:
  - operator: "Exists"

config: |
  [maintenanceResource]
  namespace = "nvsentinel"
  version = "v1alpha1"
  apiGroup = "janitor.dgxc.nvidia.com"
  
  [template]
  mountPath = "/etc/config"
  fileName = "maintenance-template.yaml"
  
  [updateRetry]
  maxRetries = 5
  retryDelaySeconds = 10

maintenanceResource:
  rebootResource:
    name: rebootnodes
  apiGroup: janitor.dgxc.nvidia.com
  namespace: nvsentinel
  version: v1alpha1
  template:
    mountPath: /etc/fault-remediation/templates
    fileName: maintenance-template.yaml

logCollector:
  enabled: false
  manifestFileName: log-collector-job.yaml
  image:
    repository: ghcr.io/nvidia/nvsentinel/log-collector
    pullPolicy: IfNotPresent
  uploadURL: "http://nvsentinel-incluster-file-server.nvsentinel.svc.cluster.local/upload"
  gpuOperatorNamespaces: "gpu-operator"
  enableGcpSosCollection: false
  enableAwsSosCollection: false
