# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Integration Tests - GCP

on:
  workflow_dispatch: {}  # allow manual runs for testing
  push:
    branches:
      - main
      - feature/oidc-gcp

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  copy-images:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      IMAGE_TAG: main-27ca26d
      TARGET_REG: us-docker.pkg.dev
      TARGET_REPO: nvsentinel
      CRANE_VERSION: "0.20.6"
      IDENTITY_PROVIDER: "projects/1015254933832/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
      SERVICE_ACCOUNT: "github-actions-user@nv-dgxck8s-20250306.iam.gserviceaccount.com"
      PROJECT_ID: "nv-dgxck8s-20250306"
      CAPACITY_RESERVATION: "projects/nv-dgxcloudprodgsc-20240206/reservations/gsc-a3-megagpu-8g-shared-res-2"
      REGION: "europe-west4"
      GPU_NODE_ZONE: "europe-west4-b"

    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      # Auth
      - name: Get AuthN Token
        id: auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093  # v3
        with:
          token_format: access_token
          workload_identity_provider: ${{ env.IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      # Cluster
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db  # v3.0.1
        with:
          version: '>= 543.0.0'

      - name: Create Cluster
        id: create-cluster
        shell: bash
        env:
          TARGET_REG: "${{ env.TARGET_REG }}/${{ env.PROJECT_ID }}/${{ env.TARGET_REPO }}"
          GPU_NODE_CAPACITY_RESERVATION: "${{ env.CAPACITY_RESERVATION }}"
          CLUSTER_NAME_SUFFIX: ${{ github.run_id }}
          REGION: ${{ env.REGION }}
          GPU_NODE_ZONE: ${{ env.GPU_NODE_ZONE }}
        run: |
          tests/uat/gcp/cluster-up.sh
          tests/uat/gcp/cluster-pool.sh

      # Test
      - name: Install NVS
        shell: bash
        env: 
          CSP: "gcp"
          NVSENTINEL_VERSION: ${{ env.IMAGE_TAG }}
        run: tests/uat/install-apps.sh

      - name: Run UAT Tests
        shell: bash
        run: tests/uat/tests.sh

      # Teardown
      # TODO: re-enable once app install is stable
      # - name: Destroy Cluster
      #   if: always() && steps.create-cluster.outcome != 'skipped'
      #   shell: bash
      #   env:
      #     CLUSTER_NAME_SUFFIX: ${{ github.run_id }}
      #   run: tests/uat/gcp/cluster-down.sh